[tools]
bat = "latest"
chezmoi = "2"
delta = "latest"
fd = "latest"
fzf = "latest"
gopass = "1"
jq = "latest"
lazygit = "latest"
make = "latest"
neovim = "0.12"
oh-my-posh = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
tmux = "3.7b"
tree-sitter = "latest"
vals = "latest"
zoxide = "latest"

[settings]
lockfile = true
