[tools]
bat = "latest"
chezmoi = "2"
delta = "latest"
dotnet = "10"
fd = "latest"
fzf = "latest"
go = "1"
golangci-lint = "latest"
gopass = "1"
helm = "3"
helmfile = "1"
java = "temurin-11.0.24+8"
jq = "latest"
k9s = "latest"
kubectl = "latest"
lazygit = "latest"
make = "latest"
neovim = "0.12"
node = "lts"
oh-my-posh = "latest"
opencode = "latest"
pi = "latest"
pulumi = "3"
python = "3.14"
ripgrep = "latest"
rust = "1"
shellcheck = "latest"
shfmt = "latest"
terraform-docs = "latest"
tmux = "3.7b"
tree-sitter = "latest"
trivy = "latest"
uv = "latest"
vals = "latest"

[settings]
lockfile = true
